version: '2.1'
services:
    app:
        image: dunai
        network_mode: "bridge"
        environment:
            PYTHONUNBUFFERED: 0
            DJANGO_SETTINGS_MODULE: 'dunai.settings.dev'
        command: >
            /bin/bash -c "
                while ! nc -z postgres 5432
                do
                    echo Waiting for PostgreSQL
                    sleep 1
                done
                ./manage.py migrate
                ./manage.py runserver 0.0.0.0:8000
            "
        volumes:
            - ../..:/root/dunai
        links:
            - postgres
        ports:
            - 8000:8000
    postgres:
        image: postgres:9.6
        network_mode: "bridge"
        environment:
            POSTGRES_DB: dunai
            POSTGRES_USER: dunai
            POSTGRES_PASSWORD: dunai

