# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
