# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
