# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0004_project_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stars',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
