version: '2.1'
volumes:
    static:
services:
    app:
        image: dunai
        environment:
            PYTHONUNBUFFERED: 0
            DJANGO_SETTINGS_MODULE: 'dunai.settings.prod'
        command: >
            /bin/bash -c "
                ./manage.py collectstatic --no-input
                ./manage.py migrate
                ./manage.py runserver 0.0.0.0:8000
            "
        links:
            - postgres
        volumes:
            - static:/root/dunai/static
        networks:
            main:
                aliases:
                    - app
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_DB: biobank
            POSTGRES_USER: biobank
            POSTGRES_PASSWORD: biobank
        networks:
            main:
                aliases:
                    - postgres
    nginx:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        volumes_from:
            - app:ro
        networks:
            main:
                aliases:
                    - nginx
networks:
    main:

