version: '2.1'
volumes:
    static:
    media:
services:
    app:
        image: dunai
        environment:
            PYTHONUNBUFFERED: 0
            DJANGO_SETTINGS_MODULE: 'dunai.settings.prod'
        command: >
            /bin/bash -c "
                while ! nc -z postgres 5432
                do
                    echo Waiting for PostgreSQL
                    sleep 1
                done
                ./manage.py collectstatic --no-input
                ./manage.py migrate
                ./manage.py runserver 0.0.0.0:8000
            "
        links:
            - postgres
        volumes:
            - static:/root/dunai/static
            - media:/root/dunai/media
        networks:
            main:
                aliases:
                    - app
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_DB: dunai
            POSTGRES_USER: dunai
            POSTGRES_PASSWORD: dunai
        networks:
            main:
                aliases:
                    - postgres
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        volumes_from:
            - app:ro
        networks:
            main:
                aliases:
                    - nginx
networks:
    main:

